# CLAUDE.md — {{PROJECT_NAME}}

> Generated by `/adapt` from `projectscope.md`. Edit `projectscope.md` and the
> templates under `.claude/templates/` instead of this file — it is overwritten
> on every adapt.

## Project Overview

**{{PROJECT_NAME}}** — {{PITCH}}

- **Domain:** {{DOMAIN}}
- **Target users:** {{TARGET_USERS}}
- **Key entities:** {{KEY_ENTITIES}}

## Stack

| Layer    | Choice                                            |
|----------|---------------------------------------------------|
| Frontend | Next.js 16 (App Router) · React 19 · Tailwind 4 · shadcn/ui |
| Backend  | {{BACKEND}}                                       |
| Auth     | {{AUTH}}                                          |
| Testing  | {{TESTING}}                                       |
| Deploy   | {{DEPLOY}}                                        |

## Existing surface (auto-detected)

- Frontend pages: {{EXISTING_PAGES}}
- Backend routes: {{EXISTING_ROUTES}}

## Conventions

{{CONVENTIONS}}

Baseline (always apply, even if conventions are unspecified):

- TypeScript strict everywhere. Avoid `any`.
- Conventional Commits.
- Frontend ↔ backend calls go through `frontend/src/lib/api.ts`.
- Use `lib/supabase/server.ts` in RSC/route handlers, `lib/supabase/client.ts` in browser code. Never mix.

## Notes

{{NOTES}}

## Key Commands

```bash
pnpm install
pnpm dev                        # frontend :3000 + backend :4000
pnpm build
pnpm --filter frontend dev
pnpm --filter backend dev
```

## Agents available

After `/adapt` runs, these agents are available in `.claude/agents/`:

- `code-reviewer` — reviews diffs for {{PROJECT_NAME}}.
- `feature-planner` — plans new features against the current page/route layout.
- `stack-specialist` — answers stack questions in the context of {{PROJECT_NAME}}.

Skills under `.claude/skills/` cover project conventions and feature
scaffolding for this stack.

## When in doubt

1. Re-read this file.
2. Check `.claude/agents/` for a specialist.
3. Match existing patterns in `frontend/src/` and `backend/src/` before
   inventing new ones.
